# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "MSYS Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "ZIP")
SET(CPACK_IGNORE_FILES "/installer/;/doc/design/;/doc/develdoc;/doc/website/;/_CPack_Packages/;/CMakeCache\\.txt$;/install_manifest\\.txt$;/xmlversion_loc\\.txt$;/config\\.h$;/version\\.h$;/doxygen_config$;/\\.svn/;/\\.dir/;/CMakeFiles/;cmake_install\\.cmake$;CPackConfig\\.cmake$;CPackSourceConfig\\.cmake$;\\.bak$;\\.flc$;#.*#$;~$;\\.~.*;\\.xcf$;\\.xcf\\.bz2$;\\.psd$;\\.exe$;/sd2-.*$;/speed-dreams-2$;/xmlversion$;\\.zip$;\\.tar\\.bz2$;\\.tar\\.gz$;\\.tar\\.Z$;\\.tar\\.7z$;/VTune/;/Release/;/Debug/;/RelWithDebInfo/;/MinSizeRel/;/release/;/debug/;/relwithdebinfo/;/minsizerel/;\\.sln$;\\.suo$;\\.ncb$;\\.vcproj*$;\\.dll$")
SET(CPACK_INSTALLED_DIRECTORIES "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/speed-dreams-2-build")
SET(CPACK_MODULE_PATH "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "Speed Dreams 2.1-beta")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "CreateShortCut \"$DESKTOP\\Speed Dreams 2.1-beta.lnk\" \"$INSTDIR\\bin\\speed-dreams.exe\"")
SET(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "Delete \"$DESKTOP\\Speed Dreams 2.1-beta.lnk\"")
SET(CPACK_NSIS_HELP_LINK "http:\\\\www.speed-dreams.org")
SET(CPACK_NSIS_INSTALLED_ICON_NAME "$INSTDIR\\bin\\speed-dreams.exe")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MENU_LINKS "http:\\\\www.speed-dreams.org;Project Homepage")
SET(CPACK_NSIS_MUI_ICON "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject\\data\\data\\icons\\icon.ico")
SET(CPACK_NSIS_PACKAGE_NAME "Speed Dreams 2.1-beta")
SET(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\www.speed-dreams.org")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "http:\\\\www.speed-dreams.org")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "c:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Speed Dreams (an Open Motorsport Sim) is a racing simulation that allows you to drive in races against opponents simulated by the computer ; it is GPL 2+ and has been forked from TORCS in late 2008")
SET(CPACK_PACKAGE_EXECUTABLES "speed-dreams;Start Speed Dreams")
SET(CPACK_PACKAGE_FILE_NAME "speed-dreams-2.1-beta-src")
SET(CPACK_PACKAGE_ICON "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject\\data\\data\\img\\header.bmp")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "speed-dreams-2.1-beta")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Speed Dreams 2.1-beta")
SET(CPACK_PACKAGE_NAME "Speed Dreams")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "the Speed Dreams team")
SET(CPACK_PACKAGE_VERSION "2.1-beta")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject/COPYING.txt")
SET(CPACK_RESOURCE_FILE_README "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject/README.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "c:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "/installer/;/doc/design/;/doc/develdoc;/doc/website/;/_CPack_Packages/;/CMakeCache\\.txt$;/install_manifest\\.txt$;/xmlversion_loc\\.txt$;/config\\.h$;/version\\.h$;/doxygen_config$;/\\.svn/;/\\.dir/;/CMakeFiles/;cmake_install\\.cmake$;CPackConfig\\.cmake$;CPackSourceConfig\\.cmake$;\\.bak$;\\.flc$;#.*#$;~$;\\.~.*;\\.xcf$;\\.xcf\\.bz2$;\\.psd$;\\.exe$;/sd2-.*$;/speed-dreams-2$;/xmlversion$;\\.zip$;\\.tar\\.bz2$;\\.tar\\.gz$;\\.tar\\.Z$;\\.tar\\.7z$;/VTune/;/Release/;/Debug/;/RelWithDebInfo/;/MinSizeRel/;/release/;/debug/;/relwithdebinfo/;/minsizerel/;\\.sln$;\\.suo$;\\.ncb$;\\.vcproj*$;\\.dll$")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/CIS 3238/speed-dreams-src-base-2.1.0-beta/SpeedDreamsForkProject/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "speed-dreams-2.1-beta-src")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "win32-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "4")
